export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPLOAD_FILE = 'UPLOAD_FILE'
export const GET_USER = 'GET_USER'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_UNVERIFIED_ADMINS = 'GET_UNVERIFIED_ADMINS'
export const GET_PARTICULAR_USERS = 'GET_PARTICULAR_USERS'
export const VERIFY_ADMINS = 'VERIFY_ADMINS'
export const LOADER = 'LOADER'




